# Generated by Django 4.2 on 2025-05-09 05:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=200)),
                ('receiver_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('legitimate', 'Legítima'), ('possibly_fraudulent', 'Posiblemente Fraudulenta'), ('fraudulent', 'Fraudulenta')], default='legitimate', max_length=20)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transacción',
                'verbose_name_plural': 'transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('legitimate_count', models.IntegerField(default=0)),
                ('possibly_fraudulent_count', models.IntegerField(default=0)),
                ('fraudulent_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'estadística de transacción',
                'verbose_name_plural': 'estadísticas de transacciones',
                'ordering': ['-date'],
            },
        ),
    ]
