# Generated by Django 3.2.19 on 2025-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('features_used', models.JSONField()),
                ('model_file', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('auc', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'modelo de fraude',
                'verbose_name_plural': 'modelos de fraude',
            },
        ),
        migrations.CreateModel(
            name='TransactionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('sender_id', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('hour_of_day', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('is_weekend', models.BooleanField()),
                ('sender_avg_amount', models.FloatField(default=0.0)),
                ('sender_transaction_count', models.IntegerField(default=0)),
                ('sender_transaction_frequency', models.FloatField(default=0.0)),
                ('amount_deviation', models.FloatField(default=0.0)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('is_fraud', models.BooleanField(default=False)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'característica de transacción',
                'verbose_name_plural': 'características de transacciones',
            },
        ),
        migrations.CreateModel(
            name='UserActivityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('avg_transaction_amount', models.FloatField(default=0.0)),
                ('max_transaction_amount', models.FloatField(default=0.0)),
                ('min_transaction_amount', models.FloatField(default=0.0)),
                ('std_transaction_amount', models.FloatField(default=0.0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('fraudulent_transactions', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('common_transaction_hours', models.JSONField(default=list)),
                ('common_transaction_days', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
            },
        ),
    ]
